### ISSUE TITLE
IHostingEnvironment.ApplicationName conflict

### ISSUE THREAD

**Issue by mike-schenk** [JasperFx/jasper#280]
ASP.Net Core [assumes](https://github.com/aspnet/Hosting/issues/1179) that the IHostingEnvironment.ApplicationName is equal to an assembly name. Specifically, it expects it to be the main assembly for the site.

The following exception is thrown from `JasperRuntime.For<OutboxSampleApp>()` with 
```
    public class OutboxSampleApp : JasperRegistry
    {
        public OutboxSampleApp()
        {
            Http.UseStartup<Startup>();
        }
    }
```
The same exception (with a slightly different stack trace) is thrown from `.Build()` in
```
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseJasper<OutboxSampleApp>()
        .Build();
```

```System.IO.FileNotFoundException: Could not load file or assembly 'OutboxSampleApp, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'OutboxSampleApp, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.DiscoverAssemblyParts(String entryPointAssemblyName)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at OutboxInMVCWithMarten.Startup.ConfigureServices(IServiceCollection services) in C:\Work\GIT\jasper\src\OutboxInMVCWithMarten\Startup.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Jasper.Http.JasperStartup.ConfigureServices(IServiceCollection services) in C:\Work\GIT\jasper\src\Jasper\Http\JasperStartup.cs:line 65
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Jasper.Http.AspNetCoreFeature.activateLocally(JasperRuntime runtime) in C:\Work\GIT\jasper\src\Jasper\Http\AspNetCoreFeature.cs:line 134
   at Jasper.Http.AspNetCoreFeature.<>c__DisplayClass18_0.<Jasper.Configuration.IFeature.Activate>b__0() in C:\Work\GIT\jasper\src\Jasper\Http\AspNetCoreFeature.cs:line 115
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Jasper.JasperRuntime.<bootstrap>d__30.MoveNext() in C:\Work\GIT\jasper\src\Jasper\JasperRuntime.cs:line 241
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Jasper.JasperRuntime.For[T](Action`1 configure) in C:\Work\GIT\jasper\src\Jasper\JasperRuntime.cs:line 177
   at OutboxInMVCWithMarten.Program.Main(String[] args) in C:\Work\GIT\jasper\src\OutboxInMVCWithMarten\Program.cs:line 23
```
This is observed in the current "restructure" branch.

Removing the following lines from JasperRuntime.cs and JasperWebHostBuilderExtensions.cs respectively seems to get past the exception:
```
registry.Http.As<IWebHostBuilder>().UseSetting(WebHostDefaults.ApplicationKey, registry.ServiceName);
builder.UseSetting(WebHostDefaults.ApplicationKey, registry.ServiceName);
```

It doesn't seem that Jasper relies on the IHostingEnvironment.ApplicationName. However, removing the line from JasperRuntime does break lots of tests when they attempt to activate the AspNetCoreFeature.

**Comment by jeremydmiller** [comment]
Removing those 2 lines will break other tests using aspnet though. Those calls were added as part of the netstandard update. Good times.

**Comment by jeremydmiller** [comment]
Wanna try grabbing the `JasperRegistry.ApplicationAssembly` and using that as the application name if it exists? I'm guessing that MVC is relying on that name to know where to go scan for Controller's?

**Comment by mike-schenk** [comment]
I'll try it.
