### ISSUE TITLE
asp.net core with jasper, no longer possible to resolve DbContext

### ISSUE THREAD

**Issue by paulvanbladel** [JasperFx/jasper#423]
I have an asp.net core app, where jasper is registerd as follows:
```
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseJasper<JasperConfig>()
                .Build();
```
JasperConfig doesn't contain any DI registrations.
My regular startup.cs though, contains a registration for dbContext and for IMyService.
```
 public void ConfigureServices(IServiceCollection services)
        {
            string connectionString = "Server=(localdb)\\mssqllocaldb;Database=etc ....;

            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(connectionString));
            services.AddScoped(typeof(IMyService), typeof(MyService));
            services.AddMvc();
        }

```
Now, I have an mvc controller with following constructor:
```
public ValuesController(IMessageContext messageContext, IMyService myService, ApplicationDbContext dbContext)

        {
            _messageContext = messageContext;
            _myService = myService;
            _dbContext = dbContext;
        }
```
The Jasper messageContext and myService are resolved but dbContext is NOT resolved.
When I remove the jasper registration (and remove IMessageContext from constructor) everything works fine.

Any idea what i'm doing 'wrong'?
thx

**Comment by jeremydmiller** [comment]
There's a test in the code to prove it picks up service registrations from the Startup.ConfigureService() method, and it is passing when I tried it just now.

What do you get from the Lamar.WhatDoIHave()? If you're using Jasper's CommandLine stuff, can you do a "dotnet run -- services" and see if anything jumps out at you?

**Comment by jeremydmiller** [comment]
And if anything, this might be a Lamar issue, not Jasper per se. I haven't tried anything w/ EF yet. I can try to look at that some time soon.

**Comment by paulvanbladel** [comment]
It's maybe because of the DbContextOptions in DbContext constructor?

see: can_bootstrap_a_bus_plus_aspnetcore_app_through_jasper_registry.cs
copy/paste this in test and you will see it fails.
```
 public class Foo : IFoo
    {
        private readonly ApplicationDbContext _context;

        public Foo(ApplicationDbContext context)
        {
            _context = context;
        }
    }
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }

    }
```

**Comment by jeremydmiller** [comment]
It's possible, but the options would be registered. Do you get some kind of exception from Lamar about not being able to select a constructor maybe?

**Comment by paulvanbladel** [comment]
Hi Jeremy,
See below for the test output when I tweak your test with aforementioned ApplicationDbContext.
```
Test Name:	Jasper.Http.Testing.AspNetCoreIntegration.can_add_the_jasper_bus_to_an_aspnetcore_app.captures_registrations_from_configure_registry
Test FullName:	Jasper.Http.Testing.AspNetCoreIntegration.can_add_the_jasper_bus_to_an_aspnetcore_app.captures_registrations_from_configure_registry
Test Source:	E:\GITHUB3RD\jasper\src\Jasper.Http.Testing\AspNetCoreIntegration\can_add_the_jasper_bus_to_an_aspnetcore_app.cs : line 103
Test Outcome:	Failed
Test Duration:	0:00:07.367

Result StackTrace:	
at Lamar.IoC.Scope.GetInstance(Type serviceType, String name)
   at Lamar.IoC.Scope.GetInstance[T](String name)
   at Jasper.Generated.Jasper_Http_Testing_AspNetCoreIntegration_ApplicationDbContext_applicationDbContext.Build(Scope scope)
   at Lamar.IoC.Resolvers.ScopedResolver`1.Resolve(Scope scope)
   at Lamar.IoC.Instances.GeneratedInstance.Resolve(Scope scope)
   at Lamar.IoC.Scope.GetInstance[T](String name)
   at Jasper.Generated.Jasper_Http_Testing_AspNetCoreIntegration_IFoo_foo.Build(Scope scope)
   at Lamar.IoC.Resolvers.TransientResolver`1.Resolve(Scope scope)
   at Jasper.Http.Testing.AspNetCoreIntegration.can_add_the_jasper_bus_to_an_aspnetcore_app.captures_registrations_from_configure_registry() in E:\GITHUB3RD\jasper\src\Jasper.Http.Testing\AspNetCoreIntegration\can_add_the_jasper_bus_to_an_aspnetcore_app.cs:line 104
Result Message:	Lamar.IoC.LamarMissingRegistrationException : Unknown service registration 'options' of Microsoft.EntityFrameworkCore.DbContextOptions<Jasper.Http.Testing.AspNetCoreIntegration.ApplicationDbContext>

```

**Comment by jeremydmiller** [comment]
Huh, okay then. I'll take a look over the weekend. Thanks for the repro steps, that should make this quick.

**Comment by jeremydmiller** [comment]
@paulvanbladel The problem was in Lamar, and it's from a permutation of the generic type and scoping that got us. Think it was a hack I put in to fix some other permutation of things, but it bit us here.  I *think* I have a fix building in Lamar itself, but I wasn't able to reproduce this in Lamar's tests by itself, so we'll see.

**Comment by jeremydmiller** [comment]
Got it.
