### ISSUE TITLE
Exceptions at run time

### ISSUE THREAD

**Issue by CodingGorilla** [JasperFx/jasper#519]
I noticed these exceptions when running the dotnet commands (e.g. `dotnet run -- storage clear`):

```
Could not make an assembly reference to mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.AccessControl, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Threading.AccessControl, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at LamarCompiler.AssemblyGenerator.ReferenceAssembly(Assembly assembly)
```

This message repeats 4 - 5 times, but then the commands successfully complete, so it doesn't seem to actually break anything.  I _do not_ see these errors when I F5 the project in Visual Studio, but I do think the exceptions are happening on my VM where the API is running.  The project is a ASP.NET MVC Core 2.2 application referencing Jasper 0.9.9.

**Comment by jeremydmiller** [comment]
Weird, I haven't seen those.

**Comment by CodingGorilla** [comment]
I'm closing this, I don't see this anymore with the latest version, at least not in the new app I'm working with.  If I still see it in the original app (when I get back to it), I'll post another issue.
