### ISSUE TITLE
azure service bus Session lock lost 

### ISSUE THREAD

**Issue by chinwobble** [JasperFx/jasper#531]
Great library and love your work on dynamic roslyn compilation!

I tried the library to enqueue some work durably like this:
Essentially I have an api and a background processor that asynchronously processes messages. In this case its the same process.
```
public class HomeController : Controller
    {
        public async Task<IActionResult> Index([FromServices] IMessageContext context)
        {
            await context.Send(new Request  {  Type = "a" });
            // await context.Enqueue(new { Test = "a"});
            return Ok("");
        }
    }

    public class Request
    {
        public string Type { get; set; }
    }

    public class RequestHandler
    {
        public void Handle(Request message, IMessageContext context)
        {
             // consume the message 
        }
    }
```

here is my config
```
internal class JasperConfig : JasperRegistry
    {
        public JasperConfig()
        {
            Publish.AllMessagesTo("azureservicebus://azure/queue/outgoing");
            HttpRoutes.Enabled = false;
            // Register listeners
            Transports.ListenForMessagesFrom("azureservicebus://azure/queue/outgoing");
            
            // Explicitly registers the Azure Service Bus transport
            Include<Jasper.AzureServiceBus.AzureServiceBusTransportExtension>();
        }
    }
```

everything works as expected but I get this error in my logs
```
info: Jasper.Transports[204]
      Sending agent for azureservicebus://azure/queue/outgoing has resumed
dbug: Jasper.Transports[202]
      Received 1 message(s) from (null)
dbug: Jasper.Messages[101]
      Received Request#016ca349-5e9b-4340-8b3f-ab1b066d2136 at azureservicebus://azure/queue/outgoing from (null)
dbug: Jasper.Messages[102]
      Started processing Request#016ca349-5e9b-4340-8b3f-ab1b066d2136
dbug: Jasper.Messages[103]
      Finished processing Request#016ca349-5e9b-4340-8b3f-ab1b066d2136
info: Jasper.Messages[104]
      Successfully processed message Request#016ca349-5e9b-4340-8b3f-ab1b066d2136 from (null)
fail: Jasper.Transports[0]
      Internal failure in the Azure Service Bus QueueClient for azureservicebus://azure/queue/outgoing
Microsoft.Azure.ServiceBus.SessionLockLostException: The session lock has expired on the MessageSession. Accept a new MessageSession.
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.DisposeMessagesAsync(IEnumerable`1 lockTokens, Outcome outcome) in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\Core\MessageReceiver.cs:line 1429
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout) in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\RetryPolicy.cs:line 85
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout) in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\RetryPolicy.cs:line 107
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.CompleteAsync(IEnumerable`1 lockTokens) in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\Core\MessageReceiver.cs:line 527
   at Microsoft.Azure.ServiceBus.SessionReceivePump.CompleteMessageIfNeededAsync(IMessageSession session, Message message) in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\SessionReceivePump.cs:line 90
```

**Comment by jeremydmiller** [comment]
@chinwobble Interesting. This functionality definitely needed more real life banging. I'll be looking at this this week finally. I hadn't noticed this until today.

**Comment by jeremydmiller** [comment]
@chinwobble Hey, I think I need a little more information from you. Did the message fail to be delivered? From what I can tell right now, this is a transient error that is being logged internally from the QueueClient, but it does retry internally.

I'm going to have to leave this one open for now because I don't know:

* If there is something to fix...
* and if there is, what to do

**Comment by chinwobble** [comment]
well the code runs fine when i have the debugger attached. Its more a question why are there exceptions in the logs. Are we not using the library correctly?
I can push a sample app that demonstrates this issue if you'd like

**Comment by jeremydmiller** [comment]
@chinwobble I'm going to have to spend some time w/ the Azure Service Bus client code, but right now I think it's just a transient error connecting to ASB and that the bigger Facade around it automatically connects for you. 

I don't think there's anything you're doing wrong here, but a sample app just to see how it's being used would always be helpful. No hurry on that.

**Comment by chinwobble** [comment]
@jeremydmiller I've prepared a repo app you can run to see the error.

you'll just need to go into the `appSettings.json` and add an a service bus connection string.

Steps to repro:
1. unzip file
2. replace the connection string
3. launch the app
4, go to localhost:xxx/home/index
5. look at the logs in the console 
[jasper repro.zip](https://github.com/JasperFx/jasper/files/3686496/jasper.repro.zip)
