### ISSUE TITLE
Recovering persisted messages seems to throw an EndOfStreamException

### ISSUE THREAD

**Issue by CodingGorilla** [JasperFx/jasper#537]
While running my application in the debugger I notice a ton of these errors in the console:

```
Jasper.Transports:Error: Running Recover persisted incoming messages

System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadString()
   at Jasper.Messaging.Runtime.Envelope.readSingle(BinaryReader br)
   at Jasper.Messaging.Runtime.Envelope.Deserialize(Byte[] buffer)
   at Jasper.Persistence.Database.EnvelopeReadingExtensions.ExecuteToEnvelopes(DbCommand command, CancellationToken cancellation, DbTransaction tx)
   at Jasper.Messaging.Durability.RecoverIncomingMessages.Execute(IDurabilityAgentStorage storage, IDurabilityAgent agent)
   at Jasper.Messaging.Durability.RecoverIncomingMessages.Execute(IDurabilityAgentStorage storage, IDurabilityAgent agent)
   at Jasper.Messaging.Durability.RecoverIncomingMessages.Execute(IDurabilityAgentStorage storage, IDurabilityAgent agent)
   at Jasper.Messaging.Durability.DurabilityAgent.processAction(IMessagingAction action)
```

I also notice that durable messages don't seem to be recovered after an application restart, although I'm not sure if it's related to this exception.

**Comment by jeremydmiller** [comment]
Oh shit, I cleaned out the Envelope and eliminated a couple things. That broke the serialization for you. 

Um, this isn't in production yet is it? Could you flesh all the storage and just go from there?

**Comment by CodingGorilla** [comment]
0.9.14 is in production yes, but it seems to be "working".  I think the problem is that it will never recover a persisted message.

>Could you flesh all the storage and just go from there?

You mean _flush_ the storage?  All of the storage was always empty even while generating this exception, AFAIK.

**Comment by jeremydmiller** [comment]
I still think this was due to changing the Envelope serialization in 0.9.14 when I removed props on envelope. It could be that one version of Jasper was serializing, and another was deserializing some how.
