### ISSUE TITLE
Custom `IContinuation` based on the RaiseAlert sample throws exceptions

### ISSUE THREAD

**Issue by CodingGorilla** [JasperFx/jasper#647]
So I need to be able to allow a handler to fail up to 3 times, and then send a new message that processes the failure.  I've been using the custom `IContinuation` same called `RaiseAlert` shown here: http://jasperfx.github.io/documentation/execution/errorhandling/#sec6

My custom continuation:

```c#
private class ImageProcessorContinuation : IContinuation
{
	private readonly Exception _lastException;

	private readonly TimeSpan[] _delays = new[]
										  {
											  TimeSpan.FromMilliseconds(500),
											  TimeSpan.FromSeconds(1),
											  TimeSpan.FromSeconds(1)
										  };

	public ImageProcessorContinuation(Exception lastException)
	{
		_lastException = lastException;
	}

	public async Task Execute(IMessagingRoot root, IChannelCallback channel, Envelope envelope, IQueuedOutgoingMessages messages, DateTime utcNow)
	{
		var session = root.NewContext();

		if(envelope.Attempts <= _delays.Length)
		{
			await session.Schedule(envelope, utcNow.Add(_delays[envelope.Attempts - 1]));
			return;
		}

		if(envelope.Message is ImageProcessorRequest request)
		{
			await SendImageProcessorFailure(session, request);
			return;
		}

		var cont = new MoveToErrorQueue(_lastException);
		await cont.Execute(root, channel, envelope, messages, utcNow);
	}

	private async Task SendImageProcessorFailure(IMessageContext session, ImageProcessorRequest request)
	{
		var sendFailureMessage = new ImageProcessingFailed
								 {
									 RequestId = request.Id,
									 Reason = _lastException.ToString()
								 };
		await session.EnqueueCascading(sendFailureMessage);
	}
}
```

Attempting to reschedule the message using the `session.Schedule()` results in the following errors/log entries:

> Jasper.Messages: Debug: Finished processing ImageProcessorRequest#01711c7e-dc97-450a-850d-94b0d20fb572
> Exception thrown: 'System.NullReferenceException' in Jasper.dll
> Jasper.Messages: Debug: Finished processing ImageProcessorRequest#01711c7e-dc97-450a-850d-94b0d20fb572
> 
 ... snip ...
> 
> Exception thrown: 'System.NotSupportedException' in Newtonsoft.Json.dll
> Jasper.Transports: Information: Envelope Envelope #01711c7f-4098-45d2-b952-0f241e08fa81 to local://durable/durable was scheduled locally for 03/27/2020 14:56:57 +00:00
> Exception thrown: 'Jasper.Serialization.EnvelopeDeserializationException' in Jasper.dll
> Jasper.Messages: Debug: Received envelope#01711c7f-4098-45d2-b952-0f241e08fa81 at local://durable/durable from (null)
> Jasper.Messages: Error: Failed to process message envelope#01711c7f-4098-45d2-b952-0f241e08fa81 from (null)
> 
> Jasper.Serialization.EnvelopeDeserializationException: Unknown content-type 'application/json' and message-type 'envelope'
>    at Jasper.Serialization.MessagingSerializationGraph.Deserialize(Envelope envelope) in D:\Source\jasper\src\Jasper\Serialization\MessagingSerializationGraph.cs:line 81
>    at Jasper.Runtime.HandlerPipeline.execute(IMessageContext context, Envelope envelope) in D:\Source\jasper\src\Jasper\Runtime\HandlerPipeline.cs:line 59
> Jasper.Messages: Error: Envelope Envelope #01711c7f-4098-45d2-b952-0f241e08fa81 to local://durable/durable was moved to the error queue
> 
> Jasper.Serialization.EnvelopeDeserializationException: Unknown content-type 'application/json' and message-type 'envelope'
>    at Jasper.Serialization.MessagingSerializationGraph.Deserialize(Envelope envelope) in D:\Source\jasper\src\Jasper\Serialization\MessagingSerializationGraph.cs:line 81
>    at Jasper.Runtime.HandlerPipeline.execute(IMessageContext context, Envelope envelope) in D:\Source\jasper\src\Jasper\Runtime\HandlerPipeline.cs:line 59

**Comment by CodingGorilla** [comment]
The RaiseAlert sample is flawed, submitted #648 to correct.
