### ISSUE TITLE
Oakton logging to disposed object in Sample code

### ISSUE THREAD

**Issue by TheFellow** [JasperFx/jasper#665]
Running the sample code for the **InMemoryMediator** sample and closing the application results in an `AggregateException` for accessing a disposed object, which appears to be the logger.

Here's my error message:
```
ERROR: System.AggregateException: An error occurred while writing to logger(s). (Cannot access a disposed object.
Object name: 'EventLogInternal'.)
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'EventLogInternal'.
   at System.Diagnostics.EventLogInternal.OpenForWrite(String
 currentMachineName)
   at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName)
   at System.Diagnostics.EventLogInternal.WriteEvent(EventInstance instance, Byte[] data, Object[] values)
   at S
ystem.Diagnostics.EventLog.WriteEvent(EventInstance instance, Object[] values)
   at Microsoft.Extensions.Logging.EventLog.WindowsEventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category)
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.WriteMessage(String message, EventL
ogEntryType eventLogEntryType, Int32 eventId)
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId,
ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState st
ate, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel
, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogDebug(ILogger logger, EventId eventId, String message, Object[] args)
   at Microsoft.Extensions.Hosting.Internal.HostingLoggerExtensions.Stopping(ILogger logger)
   at Microsoft.Extension
s.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Oakton.AspNetCore.RunCommand.Execute(RunInput input)
   at Oakton.OaktonCommand`1.Oakton.IOaktonCommand.Execute(Object input)
   at Oakton.CommandRun.Execute()
   at Oakton.CommandExecutor.execute(CommandRun run)
```

**Comment by jeremydmiller** [comment]
This has all changed so much I don't think that it applies. Not seeing any trace of this now.
