### ISSUE TITLE
Jasper compilation failure in LamarCompiler.AssemblyGenerator when Handler uses ILogger

### ISSUE THREAD

**Issue by TheFellow** [JasperFx/jasper#666]
I've come across a scenario which results in an unexpected compilation failure from the Lamar code generation.

I've reproduced a minimal sample [here](https://github.com/TheFellow/JasperTest/releases/tag/Broken). It's based on a combination of the `InMemoryMediator` sample and the `Worker` sample.

The relevant code is this:
``` csharp
public class ItemCreatedHandler
{
    private readonly ILogger _logger;
    public ItemCreatedHandler(ILogger logger) => _logger = logger;

    public void Handle(ItemCreated itemCreated)
    {
        _logger.LogInformation("Item createed with id {Id}", itemCreated.Id);
        Console.ForegroundColor = ConsoleColor.Red;
        Console.WriteLine($"Item created with id {itemCreated.Id}");
        Console.ResetColor();
    }
}
```

The failure message I receive is this:
```
fail: Jasper.Messages[0]
      Exception detected:
System.InvalidOperationException: Compilation failures!

CS1513: } expected
CS7036: There is no argument given that corresponds to the required formal parameter 'cancellation' of 'JasperTestService_ItemCreated.Handle(IMessageContext, CancellationToken)'

Code:

using System.Threading.Tasks;

namespace JasperTestService_Generated
{
    // START: JasperTestService_ItemCreated
    public class JasperTestService_ItemCreated : Jasper.Runtime.Handlers.MessageHandler
    {


        public override Task Handle(Jasper.IMessageContext context, System.Threading.CancellationToken cancellation)
        {
            var itemCreated = (JasperTestService.ItemCreated)context.Envelope.Message;
            .Handle(itemCreated);
            return Task.CompletedTask;
        }

    }

    // END: JasperTestService_ItemCreated


}
   at LamarCompiler.AssemblyGenerator.Generate(String code)
   at LamarCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
   at Jasper.Runtime.Handlers.HandlerGraph.HandlerFor(Type messageType)
   at Jasper.Runtime.HandlerPipeline.ExecutorFor(Type messageType)
   at Jasper.Runtime.HandlerPipeline.execute(IMessageContext context, Envelope envelope)
   at Jasper.Runtime.HandlerPipeline.Invoke(Envelope envelope, IChannelCallback channel)
```

This is followed by this exception which I'm guessing is a side-effect of the first:
```
fail: Jasper.Messages[0]
      Exception detected:
System.InvalidOperationException: Frame chain is being re-arranged, tried to set HandlerType: JasperTestService.ItemCreatedHandler, Method: Void Handle(JasperTestService.ItemCreated) as the 'Next
   at LamarCodeGeneration.Frames.Frame.set_Next(Frame value)
   at LamarCodeGeneration.Model.MethodFrameArranger.chainFrames(Frame[] frames)
   at LamarCodeGeneration.Model.MethodFrameArranger.Arrange(AsyncMode& asyncMode, Frame& topFrame)
   at LamarCodeGeneration.GeneratedMethod.ArrangeFrames(GeneratedType type, IServiceVariableSource services)
   at LamarCodeGeneration.GeneratedType.ArrangeFrames(IServiceVariableSource services)
   at LamarCodeGeneration.GeneratedAssembly.GenerateCode(IServiceVariableSource services)
   at LamarCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
   at Jasper.Runtime.Handlers.HandlerGraph.HandlerFor(Type messageType)
   at Jasper.Runtime.HandlerPipeline.ExecutorFor(Type messageType)
   at Jasper.Runtime.HandlerPipeline.execute(IMessageContext context, Envelope envelope)
   at Jasper.Runtime.HandlerPipeline.Invoke(Envelope envelope, IChannelCallback channel)
```

The workaround appears to be as simple as accepting a contextual logger instead by adding the Type parameter:
```csharp
public class ItemCreatedHandler
{
    private readonly ILogger _logger;
    public ItemCreatedHandler(ILogger<ItemCreatedHandler> logger) => _logger = logger;

    public void Handle(ItemCreated itemCreated)
    {
        _logger.LogInformation("Item createed with id {Id}", itemCreated.Id);
        Console.ForegroundColor = ConsoleColor.Red;
        Console.WriteLine($"Item created with id {itemCreated.Id}");
        Console.ResetColor();
    }
}
```

**Comment by jeremydmiller** [comment]
Verified today. You do need to use ILogger<T> though.
